Updated Docs link in badge
MDAnalysis/membrane-curvature pull request #55
Opened 2021-07-24 21:21 UTC by ojeda-e

Fixes #53 

Docs links updated to https://membrane-curvature.readthedocs.io/en/latest/

2021-07-24 21:29 UTC, lilyminium requested changes

2021-07-24 21:29 UTC, lilyminium commented on README.md
> +[![docs](https://readthedocs.org/projects/pip/badge/)](https://membrane-curvature.readthedocs.io/en/latest/)
```suggestion
[![docs](https://readthedocs.org/projects/membrane-curvature/badge/?version=latest)](https://membrane-curvature.readthedocs.io/en/latest/)
```

My bad for not picking this up earlier, but I think it's actually picking up the build status of pip :p

2021-07-24 22:09 UTC, lilyminium commented on README.md
> +[![docs](https://img.shields.io/badge/docs-latest-brightgreen.svg)](https://membrane-curvature.readthedocs.io/en/latest/)
I'm not sure this is what you want, it looks like it's just always green. I think I pasted the right link earlier.

2021-07-24 23:18 UTC, lilyminium approved these changes
Thank you!

2021-07-25 00:31 UTC, ojeda-e commented
> Thank you!

Thanks, @lilyminium, I am receiving delayed notifications from your comments and some of my replies weren't saved :s 
Nothing important, but just letting you know. I'll merge this. Thanks again :)

2021-07-25 00:32 UTC, merged